### ISSUE TITLE
extends WeaponPlugin.Weapon

### ISSUE THREAD

**Issue by easierbycode** [16patsle/phaser3-weapon-plugin#14]
throws an error:
`Uncaught TypeError: Class constructor Weapon cannot be invoked without 'new'`

what is the proper way to do this?  I tried changing Phaser.Weapon / Phaser.Bullet to WeaponPlugin.Weapon / WeaponPlugin.Bullet with no luck ..

Here's the Phaser 2 Weapon code I am trying to migrate:

```
class Bullet extends Phaser.Bullet {

    kill() {}
    
    update() {
        this.angle++;
        this.tint   = Math.random() * 0xFFFFFF;
        super.update();
    }
}

export class PentagramBullet extends Phaser.Weapon {

    BLOWS_SHIT_UP   = true;
    hitPoints   = 8;
    skullBulletFireSound;
    
    constructor( player, game, parent = game.world, name = 'Pentagram Bullet', addToStage = false, enableBody = true, physicsBodyType = Phaser.Physics.ARCADE ) {
        super( game, parent, name, addToStage, enableBody, physicsBodyType );
        
        this.nextFire       = 0;
        this.bulletSpeed    = 600;
        this.fireRate       = 1600;
        this.bulletClass    = Bullet;

        this.createBullets( 32, 'pentagramBullet' );

        this.trackSprite( player, 60, 5, true );
    }
}
```

**Comment by 16patsle** [comment]
What is your ES6 situation? Are the classes getting transpiled to ES5? Are you importing the bundled/transpiled version of the weapon plugin or the files directly? I know there are certain incompatibilities with Babel when it comes to combining ES6 and ES5 classes made by Babel. Could it be that you are running native ES6 classes in the browser, but using a transpiled version of the plugin (I believe the only prebuilt version currently available is transpiled)?

**Comment by 16patsle** [comment]
@easierbycode Did you figure it out?

**Comment by 16patsle** [comment]
Closing this for now
