### ISSUE TITLE
There should be some validation step to warn of weird config combinations

### ISSUE THREAD

**Issue by jdotrjs** [16patsle/phaser3-weapon-plugin#3]
As an example one of the test pages was using a mix of bullets having a world border kill and also wrapping at world border which is results in some odd behaviors.

**Comment by 16patsle** [comment]
The question is at which point would it be possible to check this? If I remember the code correctly, there isn't a clear point at which all this is known, other than immediately before firing the bullets. Not sure if we would want to do it in there?

If we go with a builder style interface, maybe there will be somewhere more logical to do this then?

**Comment by 16patsle** [comment]
I'm doing the work to implement this now. Seems like putting setters on properties that could potentially cause weird config, and then calling a config validation function to check might be a reasonable approach. Only downside is that if we only log a warning to the console, they might in some cases be logged several times.

**Comment by jdotrjs** [comment]
TBH I think it's okay for logging to the console to happen several times. It should mostly be limited to when the plugin gets constructed which is not going to happen _tooooo_ many times? We could always add a flag that can be set to disable error output if we wanted that could be enabled for production builds and the like. (Related: we could have a `strict` mode that throws exceptions instead of just logging.)

**Comment by 16patsle** [comment]
Worked on this in #13
