### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by jonpedigo** [16patsle/phaser3-weapon-plugin#30]
<img width="1113" alt="Screen Shot 2022-03-09 at 8 39 14 PM" src="https://user-images.githubusercontent.com/3174683/157590750-2dd82a42-7f29-4d72-a6f0-cd534ff3d9a4.png">

I have reset my node_modules and reinstalled the package and I still run into this issue. I am importing as the docs recommend 

<img width="737" alt="Screen Shot 2022-03-09 at 8 40 55 PM" src="https://user-images.githubusercontent.com/3174683/157590866-7da9a59a-836b-4bf8-b31e-f1e12213b557.png">

Very weird behavior. I am in a create-react-app environment

**Comment by jonpedigo** [comment]
DIFFERENT ISSUE

<img width="773" alt="Screen Shot 2022-03-09 at 8 49 44 PM" src="https://user-images.githubusercontent.com/3174683/157591837-cc7f4659-f546-49a5-8c58-37dc90d54d8f.png">

When I take a different approach, I just get an error. This is from loading the WeaponPlugin.js code the same way its done in the examples

**Comment by jonpedigo** [comment]
The version of phaser i am using is 3.55.2

**Comment by jonpedigo** [comment]
Ah I see, is this only available for Arcade Physics?

**Comment by 16patsle** [comment]
Yes, it is only for Arcade Physics unfortunately. It's more or less a direct port of the similar feature from Phaser 2.7 (or around that time).

**Comment by easierbycode** [comment]
are there any plans for a Phaser 4 version?

**Comment by 16patsle** [comment]
I hope to eventually, but it's still way too early. I'll probably have to see what the physics situation ends up being first before I decide on a course of action
