### ISSUE TITLE
All thrown errors should be moved to the plugin creation / setup step if possible

### ISSUE THREAD

**Issue by jdotrjs** [16patsle/phaser3-weapon-plugin#4]
```javascript
      if (this.bulletKillType === consts.KILL_LIFESPAN) {
        if (this.bulletLifespan <= 0) {
          throw new Error('Invalid bulletLifespan; must be > 0')
        }
        bullet.data.timeEvent = this.scene.time.addEvent({
          delay: this.bulletLifespan,
          callback: bullet.kill.bind(bullet),
        })
        bullet.lifespan = this.bulletLifespan;
      }
```

I added that throw because it doesn't make sense to have a lifespan < 0 but it's not great to have things throwing while the game runs either.

When we start polishing we should update the setup phase to hide all attribute updates behind setters with validation or use a builder pattern to do as much as we can to ensure that things which will throw will happen as early as possible.

**Comment by jdotrjs** [comment]
(this is probably blocked on #3)

**Comment by 16patsle** [comment]
If we were to do this, would it be in the form of stuff like setBulletLifespan? I guess it would make sense to have those directly on the Weapon, and have it act on the bullets when they are created or something? Or would it not create the bullets until it's told to do so, making it possible to use a bunch of setter functions in between?

Another thought that came to mind is allowing to pass an options object when creating the Weapon, and allowing to set the values from there. Then we would just do some checking of the values in the constructor of Weapon.
