### ISSUE TITLE
Refactor fire method

### ISSUE THREAD

**Issue by jdotrjs** [16patsle/phaser3-weapon-plugin#5]
It's 200 lines long with minimal comments, there has got to be some cleanup we can do there

**Comment by 16patsle** [comment]
A combination of splitting out into separate functions and adding comments, I'd guess?

**Comment by 16patsle** [comment]
Started with adding some comments in `8b84adf`, next step is probably a bit of refactoring.

**Comment by 16patsle** [comment]
Did some obvious improvements at least, so should be enough for now.
